import Head from "next/head";
import * as s from "./styles";
import { Navbar } from "../components/Organisms";
import { Hero, About } from "../components/Templates";

export default function Home() {
  return (
    <s.Background>
      <Head>
        <title>Template | Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <s.Body>
        <Hero id="hero" />
        <About id="about" />
      </s.Body>
    </s.Background>
  );
}
